### ISSUE TITLE
Picking image IOS issue

### ISSUE THREAD

**Issue by sushilparajuli** [Natjs/nat-media-image#2]
http://recordit.co/IBJE4TWioq/gif/notify. App crashed on using:

// pick image from gallery
        Nat.image.pick((err, ret) => {
          console.log(ret)
        })

**Comment by acathur** [comment]
Did you install nat and nat weex module correctly?

```
npm i natjs --save
weexpack plugin add nat-media-image
```

**Comment by sushilparajuli** [comment]
Yup, I have followed the above. In android, It's working fine.

**Comment by acathur** [comment]
Can you provide the crash logs of Xcode?

**Comment by sushilparajuli** [comment]
Here is the issue I am facing : http://recordit.co/Xp1nVUWcky . And after relaunching app, getting this error mesage in iOS : http://recordit.co/vI6zbVB2Kw. Let me know your feedback on this : `This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data`

**Comment by acathur** [comment]
This is a common permission issue in iOS, you can fix it with the steps below.

1. Enter weex project root directory, open `./platforms/ios/[main project name (default is Demo)]/*-Info.plist` file

2. Add the following code into the `<dict>` tag
```xml
	<key>NSPhotoLibraryUsageDescription</key>
	<string>reason for using this permission goes here</string>
```

**Comment by sushilparajuli** [comment]
Thanks. It's working now 👍

**Comment by sushilparajuli** [comment]
Thanks. It's working now 👍
