### ISSUE TITLE
依赖的TZImagePickerController版本太低，需要升级，否则审核会不通过

### ISSUE THREAD

**Issue by PrearAnthony** [Natjs/nat-media-image#3]
如题，当前引用版本的TZImagePickerController.m的484、675行包含有 prefs:root= ，这个东西苹果已经禁用，继续使用会导致苹果审核被拒。

![1](https://user-images.githubusercontent.com/4514707/41328015-7893343c-6ef8-11e8-8ba3-51403a312295.jpg)

![2](https://user-images.githubusercontent.com/4514707/41328023-8669a686-6ef8-11e8-9bfc-d42a76104555.jpg)

**Comment by acathur** [comment]
Update TZImagePickerController to `2.1.6`, release `NatImage` `0.0.8`

**Comment by jianxiongc** [comment]
Hi Acathur,
我使用Cocopods 将NatImage 改为0.0.8  ,
提示如下错误

```

[!] CocoaPods could not find compatible versions for pod "NatImage":
  In Podfile:
    NatImage (= 0.0.8)

None of your spec sources contain a spec satisfying the dependency: `NatImage (= 0.0.8)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

```

**Comment by acathur** [comment]
在Terminal中使用`pod repo update`更新cocopods依赖版本信息
